### PR TITLE
Requirements Patching

### PR DESCRIPTION
**Pull request by HuzefaMandvi**
So I don't love this way of patching the requirements, but I think its better than asking users to go in after installing devstack and doing it manually. LMK what you think

### CODE REVIEW

**Comment by hgibson1** [comment]
You don't think it would be better to have a git patch?

**Comment by HuzefaMandvi** [comment]
What do you mean by a git patch?

**Comment by hgibson1** [comment]
Each openstack service and the requirements are git repositories. We could generate a patch then have them change openstack services using git apply <patch>

**Comment by HuzefaMandvi** [comment]
Ah I didn't know about this functionality. In that case I'll build a git patch file for the fix and put it in this repo

**Comment by hgibson1** [comment]
I have a git patch that hasn't been committed yet, although you're required to apply it from the requirements directory. Supposedly there's a way to generate patches that use either absolute paths or no path which might be a better idea.

**Comment by HuzefaMandvi** [comment]
The patch would need to be automatically applied immediately after cloning. Otherwise, stack.sh fails - the user can't manually apply it after stack.sh

**Comment by HuzefaMandvi** [comment]
If we think of a better (more modular) way to do this, we can implement it at some point in the future. For now, I think we both agree this is best quick-fix to get devstack working on centos.

**Pull request merged**
